// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// ⚠️ CHƯA CẤU HÌNH FIREBASE?
// Chạy lệnh sau trong thư mục project:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// Lệnh trên sẽ tự động ghi đè file này với config thật từ Firebase Console.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions chưa được cấu hình cho platform này.',
        );
    }
  }

  // Thay các giá trị YOUR_* bằng config từ Firebase Console
  // hoặc chạy `flutterfire configure` để tự động điền.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHH5F_HRImeJU4wP6G6fmYDwHRi7fLhSU',
    appId: '1:392562660036:web:eeee442fa210cf1b216f91',
    messagingSenderId: '392562660036',
    projectId: 'checkingo-bb56d',
    authDomain: 'checkingo-bb56d.firebaseapp.com',
    storageBucket: 'checkingo-bb56d.firebasestorage.app',
    measurementId: 'G-96GGWY6E53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgSRbrhxNM_3aJF3CRMsAMAvrxhZevKa0',
    appId: '1:392562660036:android:7f8010f53b014906216f91',
    messagingSenderId: '392562660036',
    projectId: 'checkingo-bb56d',
    storageBucket: 'checkingo-bb56d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGyq4r82O2WjjRjnCfleOQm6NgqJZ1fyk',
    appId: '1:392562660036:ios:24c743c4d3b6a37c216f91',
    messagingSenderId: '392562660036',
    projectId: 'checkingo-bb56d',
    storageBucket: 'checkingo-bb56d.firebasestorage.app',
    iosBundleId: 'com.example.checkingo',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGyq4r82O2WjjRjnCfleOQm6NgqJZ1fyk',
    appId: '1:392562660036:ios:24c743c4d3b6a37c216f91',
    messagingSenderId: '392562660036',
    projectId: 'checkingo-bb56d',
    storageBucket: 'checkingo-bb56d.firebasestorage.app',
    iosBundleId: 'com.example.checkingo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHH5F_HRImeJU4wP6G6fmYDwHRi7fLhSU',
    appId: '1:392562660036:web:c1cd090b9aeca199216f91',
    messagingSenderId: '392562660036',
    projectId: 'checkingo-bb56d',
    authDomain: 'checkingo-bb56d.firebaseapp.com',
    storageBucket: 'checkingo-bb56d.firebasestorage.app',
    measurementId: 'G-3C575G4S6G',
  );
  static bool get isConfigured =>
      !android.apiKey.startsWith('YOUR_') &&
      android.projectId != 'YOUR_PROJECT_ID';
}
